name: Check migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-migrations:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get target branch name
      uses: technote-space/get-diff-action@v6

      with:
        PATTERNS: |
          +(migrations)/*.sql
        SEPARATOR: ", "

  second-step:
    needs: check-migrations
    steps:
      - name: Test
        if: ${{env.GIT_DIFF_FILTERED}} != ''
        run: echo "Run migrations..."

  add-comment:
    needs: second-step 
    steps:
      - name: Add PR comment
        uses: actions/github-script@v6
        env:
          MIGRATION_FILES: ${{env.GIT_DIFF_FILTERED}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { MIGRATION_FILES } = process.env
            const emoji = MIGRATION_FILES === '' ? ':+1' : ':eyes'

            if (MIGRATION_FILES) {
              const payload = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Found migrations: ${emoji}` + MIGRATION_FILES
              }
              await github.rest.issues.createComment(payload)
            }
