name: Check migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compare-branches:
    steps:
      - name: Run check migrations action
        uses: ./.github/actions/validateMigrations
        with:
          folder: 'some/folder/with/migration'
