name: Check migrations

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compare-branches:
    steps:
      uses: ./.github/actions/validateMigrations
      with:
        folder: 'some/folder/with/migration'
